import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/main.ts',
    'src/communities-staged-rehearsal.ts',
    'src/verify-role-boundary.ts',
    'src/verify-media-runtime-role.ts',
    'src/verify-chat-push-foundation.ts',
    'src/verify-chat-push-foundation-operational.ts',
    'src/verify-chat-push-foundation-contour.ts',
    'src/verify-eligibility-payment-acl-boundary.ts',
    'src/provision-eligibility-payment-acl.ts',
    'src/provision-communities-staging-role-split.ts',
    'src/produce-communities-staging-role-split-inventory.ts',
    'src/compare-communities-staging-role-split-inventories.ts',
    'src/verify-communities-staging-role-split-inventory-artifact.ts',
    'src/verify-eligibility-payment-runtime-role.ts',
    'src/provision-eligibility-payment-cup-projection-acl.ts',
    'src/cup-player-level-projection-rehearsal.ts',
    'src/provision-eligibility-payment-participation-command-acl.ts',
    'src/participation-command-foundation-rehearsal.ts',
  ],
  format: ['esm'],
  target: 'node22',
  platform: 'node',
  bundle: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  noExternal: [/^@phub\//],
});
