name: phub-timeweb-beta-ingress

services:
  caddy:
    image: caddy@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
    restart: unless-stopped
    ports:
      - '0.0.0.0:80:80/tcp'
      - '0.0.0.0:443:443/tcp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      beta:
        ipv4_address: 172.30.26.10
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: '3'

networks:
  beta:
    external: true
    name: phub-timeweb-beta

volumes:
  caddy_data:
    name: phub-timeweb-beta-caddy-data
  caddy_config:
    name: phub-timeweb-beta-caddy-config
